### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by weimoji** [riedlma/topictiling#7]
Hello,
When I try to segment Chinese document on Windows 10 system with script:
bash topictilling.bat -ri 5 -tmd topicmodel -tmn model-final -fp "*txt" -fd files_to_segment
I encounter the following error
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/IllegalClassException
        at org.uimafit.factory.CollectionReaderFactory.createDescription(CollectionReaderFactory.java:217)
        at org.uimafit.factory.CollectionReaderFactory.createDescription(CollectionReaderFactory.java:208)
        at org.uimafit.factory.CollectionReaderFactory.createCollectionReader(CollectionReaderFactory.java:154)
        at org.uimafit.factory.CollectionReaderFactory.createCollectionReader(CollectionReaderFactory.java:118)
        at de.tudarmstadt.langtech.semantics.segmentation.segmenter.RunTopicTilingOnFile.<init>(RunTopicTilingOnFile.java:102)
        at de.tudarmstadt.langtech.semantics.segmentation.segmenter.RunTopicTilingOnFile.main(RunTopicTilingOnFile.java:94)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.IllegalClassException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
What does this error mean? What should I do?
Thanks!

**Comment by weimoji** [comment]
Before execute topictilling, I execute JGibbLDA with command
java -cp bin:lib/args4j-2.0.6.jar jgibblda.LDA -est F:\JGibbLDA-v.1.0\model\ -dfile 01.txt
and get five model-final files.
Did I do anything wrong?
